var projects =
[
[{name: 'Title', value: 'ATG Battle Lab (11038)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11038'},{name: 'ProjectManager', value: 'arron.leverman'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'ITAS - 10971'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10971'},{name: 'ProjectManager', value: 'arron.leverman'},{name: 'Customer', value: '19;#USN'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: 'Tactical Training Group Pacific (TTGP) has a continuing requirement to provide the US Pacific Fleet with training to conduct effective naval and joint operations across the spectrum of combat operations. TTGP's mission is to provide advanced tactical training to improve war-fighting proficiency to meet the unified commander's requirements. This training requirement spans individual units, Amphibious Readiness Groups (ARG), Carrier Strike Groups (CSG) and Carrier Strike Forces (CSF).
TTGP distributes virtual training to ships and other training facilities, as directed in the Fleet Synthetic Training (FST) Program. TTGP has been designated as Commander, Pacific Fleet’s (CPF) Executive Agent (EA) for the CPF In port Training Architecture (ITA), the FST backbone architecture, which consists of the Navy’s Continuous Training Environment (NCTE) and other command and control (C2) related systems. TTGP is the primary Pacific Fleet persistent NCTE node as well as the site for a persistent node for the Joint National Training Capability Training and Enterprise Network (JTEN). As such, it supports two-thirds of Commander THIRD Fleet’s (C3F) Fleet Response Training Plan (FRTP) through distributed training events and a growing list of distributed joint and coalition training events to include Ballistic Missile Defense Exercises (BMDEX). Tactical Training Group, Pacific’s Detachment Yokosuka (TTGPDY) Fleet Battle Lab (FBL) supports the execution of the Commander SEVENTH Fleet Training Plan (SFTP) for Forward Deployed Naval Forces (FDNF) units. As EA, TTGP provides distributed training architecture support to the Afloat Training Groups in each Pacific Fleet Concentration Area (FCA). Training events are controlled and distributed from the TTGP Distributed Training Control Center (DTCC) and the four FBLs.
The project requires the contractor to provide ITA development, configuration, operation, and management technical support at San Diego, CA (TTGP/DTCC/FBL-SD/C3F); Yokosuka, Japan (FBL-TTGPDY); Pearl Harbor, Hawaii (FBL-MP); and Everett, WA (FBL-PNW). Contractor services cover a wide range of engineering and technical support relative to FST. Contractor develops and improves technical planning documents, instructions, and guidelines for fleet and unit-level synthetic training. It also provides operational systems integration support to the ITA, through sophisticated engineering and related tasking, to include, but not limited to full-scale development, and updates to hard data and training tools. Contractor will utilize current training tools/systems, to conduct training for Pacific Fleet (PACFLT) mission-critical FST. Contractor will also recommend changes to these tools and provide recommendations for instruction update/improvement in support of PACFLT and Ballistic Missile Defense (BMD) training programs.
The Contractor provides a technical plan of drawings, configurations, systems capabilities and limitations; to describe a training architecture incorporating Command, Control, Communications, Computers, Collaboration, and Intelligence (C5I) systems, training systems, and networks that will achieve training objectives. The Contractor develops test plans to validate the training architecture performance. The Contractor maintains and configures training tools. The Contractor provides Subject Matter Expert (SME) technical support and operates training tools that achieve the training objectives. The Contractor reports on training objective achievement and training architecture effectiveness. The Contractor provides BMD technical and operations support.
'}]
,[{name: 'Title', value: 'AED Maintenance Engineering Spt - 10931.001'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10931'},{name: 'ProjectManager', value: 'rebecca.roberson'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Provide Technical Support – Engineering Services for the Aviation Missile Research, Development and Engineering Center (AMRDEC), Aviation Engineering Directorate (AED), Maintenance Engineering Division (AEM).  This support provides a broad spectrum of engineering and technical support encompassing maintenance policies and procedures; upgrades and repairs; technical data revision/ improvement; prototyping, and corrosion prevention and control. Our experts will develop and implement new maintenance concepts in support of Army and multi-service aircraft, associated power plants, components and subassembly items. Continue to improve procedures and processes through frequent and vigilant observation while visiting depot repair shops. Assist the depot artisans in assuring proper processes are followed and evaluating/ resolving engineering related production problems affecting quality and schedule. Our field and depot liaison engineering services to the Army, Navy, Air Force and FMS will keep the warfighter equipped with the world’s best quality aircraft and components.'}]
,[{name: 'Title', value: 'Tech Loop Spt - 10057.060'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10057'},{name: 'ProjectManager', value: 'rebecca.roberson'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'UHPMO Programmatic Spt - 10234.038'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10234'},{name: 'ProjectManager', value: 'rebecca.roberson'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Provides Foreign Military Sales (FMS) support for Blackhawk within the UHPO, PEO Aviation.  '}]
,[{name: 'Title', value: 'AED Mission Equipment Division Programmatic Spt - 10931.006'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10931'},{name: 'ProjectManager', value: 'rebecca.roberson'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'AED Propulsion Spt - 11009.002'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11009'},{name: 'ProjectManager', value: 'rebecca.roberson'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CCAD Production Spt - 10931.002'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10931'},{name: 'ProjectManager', value: 'rebecca.roberson'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CTMMC (10742)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10742'},{name: 'ProjectManager', value: 'brian.mcgivern'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'a. Continuity of Operations (COOP) Planning
b. Strategic Communications Team prepare briefs, talking points, answer National Security Staff RFIs
c. Mission Management Support
d. Mission Dataflow Management
e. Production Line Staff Action Officers
f. Database Records Management
'}]
,[{name: 'Title', value: 'Steelyard (10862)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10862'},{name: 'ProjectManager', value: 'bruce.roberts'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CCMR GPOI (11097)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11097'},{name: 'ProjectManager', value: 'thomas.sweeney'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CCMR HYBRID (11069)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11069'},{name: 'ProjectManager', value: 'thomas.sweeney'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CCMR In-Residence (11109)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11109'},{name: 'ProjectManager', value: 'thomas.sweeney'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CTL (10878)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10878'},{name: 'ProjectManager', value: 'carcie.graves'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'Camber’s Conformance Test Laboratory (CTL) operates as a third party conformance test laboratory to provide conformance testing in support of the Critical Reagent Program’s (CRP) mission.  Camber’s CTL has been instrumental in developing the unique processes and procedures used for the conformance testing of CRP lateral flow immunoassays(LFI) used in a variety of detection platforms (i.e. HHA, JBPDS, and JPS).  Prior to the existence of the Camber CTL, a formalized third party QA/QC process did not exist in the acceptance of the manufactured LFI and electrochemiluminescence (ECL) assays. Camber’s CTL provides Conformance Test Reports (CTR) to CRP and provides other testing support as directed. Camber’s CTL has a Quality Management System (QMS) that is accredited to ISO-17025, which is a standard used for calibration and testing laboratories.  The accreditation meets or exceeds the requirements of ISO-9001.  The CTL has a Secret level facility clearance granted by the Defense Security Service, and all CTL staff members have Secret level personnel security clearances.'}]
,[{name: 'Title', value: 'VBA Skills Certification Testing - 10958'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10958'},{name: 'ProjectManager', value: 'carol.faben'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '4;#FFP LOE'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'OneSAF I2S - 10729.003/11070.00'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10729/11070'},{name: 'ProjectManager', value: 'charles.frye'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'MCICOM'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'joseph.ammon'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'PACAF Sqdn Spt (10953.0005)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10953'},{name: 'ProjectManager', value: 'curt.conrad'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'Force Risk Reduction (FR2) – 11029/11031'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11029'},{name: 'ProjectManager', value: 'curtis.kanahele'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '5;#CPFF LOE'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'BSSG (11046)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11046'},{name: 'ProjectManager', value: 'david.parkinson'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'R2TD (10954)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10954'},{name: 'ProjectManager', value: 'david.holliday'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'AF Mod & Sim Svc Spt - AFMS3 (10953.0001)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10953'},{name: 'ProjectManager', value: 'eliot.ramey'},{name: 'Customer', value: '15;#USAF'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: 'The purpose of this Task Order (TO) is to provide specialized Modeling & Simulation Support in the Live, Virtual and Constructive (M&S/LVC) operational, technical, and innovative support services for the Joint M&S Community to assist in the Government’s integration of “Live” training with realistic simulation environments. The Air Force Life Cycle Management Center (AFLCMC) at Wright-Patterson Air Force Base, OH is the lead organization supported by this TO. Previously Air Force Agency for Modeling and Simulation was the primarily supported organization. This TO provides support to the Joint M&S Community mainly composed of AF and other Department of Defense (DoD) organizations, but at times may support other Federal agencies. 
The Air Force M&S initiative focuses on simulation as the critical capability for augmenting live resources and processes to support the National Preparedness Cycle (Plan, Organize & Equip, and Train). M&S is seen as an enabler for decision making and enhancing human performance instead of solely relying on the need for expending resources through live capabilities. In today’s current environment where funding and resources are limited yet threats to our nation’s security still remain requires a higher demand to use M&S/LVC to train, test, and equip the nation’s preparedness and resiliency. The term “LVC” refers to all aspects of training, simulations, exercises and supporting infrastructures, models, databases, tools, and services which support the operational training community.
'}]
,[{name: 'Title', value: 'USAF ISR-U2 (10953.0003)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10953'},{name: 'ProjectManager', value: 'eliot.ramey'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '4;#FFP LOE'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'ACB BLAST'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'eric.fitzwater'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'AIRWORKS Program Office Spt - 11011'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11011'},{name: 'ProjectManager', value: 'eric.fitzwater'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'ARDEC RISK MGT SPT - 11015'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11015'},{name: 'ProjectManager', value: 'eric.fitzwater'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'PM CAS - 11007'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11007'},{name: 'ProjectManager', value: 'eric.fitzwater'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'COCOM Spt - 10057.T05/10957.012/10224.033'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10057/10957/10224'},{name: 'ProjectManager', value: 'eugene.pellecchia'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'Provide technical and training service support to US Pacific Command (USPACOM), US Central Command (USCENTCOM), US Southern Command (USSOUTHCOM) and US Transportation Command (USTRANSCOM) in the implementation of the Joint Training System (JTS), '}]
,[{name: 'Title', value: 'FMS Taiwan Han Kuang Spt - 11018'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11018'},{name: 'ProjectManager', value: 'eugene.pellecchia'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'USSS Einfo Extranet Support (1010952.0001)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'virginia.fisher'},{name: 'Customer', value: '22;#USSS'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'Management, support and development of the USSS eInformation Network
Management of network that supports external applications
Management and development of USDollars website
Management and development of eLibrary website
Administration of the websites
Helpdesk assistance to USSS administrators
Demonstration & training
'}]
,[{name: 'Title', value: 'NAVAIR 7.2.6 CYBER SEC SP (11067)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11067'},{name: 'ProjectManager', value: ''},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'AO Mainframe Support/LA Systems (1001927)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: '1001927'},{name: 'ProjectManager', value: 'jillian.green'},{name: 'Customer', value: '1;#AO'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'VBA TPSS Training Evaluation & Management - 10900'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10900'},{name: 'ProjectManager', value: 'ingrid.mellone'},{name: 'Customer', value: '23;#VA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'The Department of Veterans Affairs (VA) through the Veterans Benefits Administration (VBA), Technical Training and Evaluation Office (TT&E) (NOTE: In 2015, the name was changed to Training and Performance Improvement Directorate, TPI) requested support for the purpose of creating , updating, or implementing all phases of the Instructional Systems Development process; Technical Training and Performance Support System (TPSS) products; and providing related training infrastructure support and evaluation for VBA training efforts. This project is a continuation of VBA’s existing TPSS and training event support for all services—designed to provide training and performance support to VBA employees on critical job tasks. VBA has identified six tasks necessary to accomplish the TPSS and training event support.
Task One—provide a detailed project management plan (PMP) and briefing for the project team. In constructing the PMP, Camber was tasked with providing details on Risk, Quality, our technical management approach, work breakdown structure and schedule, cost requirements, proposed personnel and travel.
Task Two—a competency-based individual training assessment package. Camber was tasked with developing assessment instruments for the purpose of (1) conducting an initial assessment ranging across all proficiency levels, e.g. entry, intermediate, and journey relative to critical positions within the listed Service, and (2) an annual reassessment for each position using test results from the discreet training events completed during the year for the purpose of testing performance improvement along the proficiency continuum.
Task Three—advanced evaluation analytic structure and dashboard package using (1) existing level 1 and level 3 survey responses, (2) level 2 outcomes as available, (3) training information recorded in VBA’s learning management system, (4) publicly available production and quality results, and (5) others to be identified.
Task Four—support for implementation and modifications to VBA’s Strategic Plan for Training and Workforce Development. For our implementation support, Camber was tasked with supporting Quarterly Briefings where we were to create standard operating procedures for each briefing; coordinating with VBA elements when collecting information necessary to populate and/or update presentation packets; meeting facilitation; updating slide content post meeting; and providing the Chief Learning Officer with information captured during the briefing. For our modification support, Camber was tasked with updating sections of the VBA’s Strategic Plan based on (1) directions from the Chief Learning Officer or designee; (2) issued identified during the quarterly briefings; and (3) changes in VBA, VA or Governmental policies, laws, or governance.
Task Five—create a VBA Training Portal Package for the purpose of providing an integrated group of web-pages serving as a single starting point for finding VBA training, information, training, and policy.
Task Six—create a Training Manager’s Development Program Package for the purpose of supporting 56 Regional Office Training Managers. Camber was tasked with (1) the identification of existing training relevant to the different levels of experience, (2) creating curricula within VBA’s learning management system, (3) identifying topics as well as organizing monthly web-based meeting with the Training Managers, and (4) creating and organizing an annual web-based conference.
'}]
,[{name: 'Title', value: 'JMASS III/IV - AO (1001850/1010981/1011040/1011063)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'chris.jacobs'},{name: 'Customer', value: '1;#AOUSC'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'IMSG provides high-end IT professional services to the Administrative Office of US Courts, including full life cycle software development, application support, database support, enterprise infrastructure support,  migration of major systems to improve business processes, help desk, maintenance support services, planning and analysis, project management, independent verification and validation (IV&V),  Agile software and systems engineering
300+ FTEs across three geographic locations
Supports 25-35 AO managers on a daily basis
Supported for over 20 years (since JMAS I)
'}]
,[{name: 'Title', value: 'FAA UAS SPT-LONESTAR - 10936'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10936'},{name: 'ProjectManager', value: 'jason.casey'},{name: 'Customer', value: '12;#Texas A&M'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'Act as the Lead Systems Integrator (LSI) for the State of Texas as one of six congressionally mandated Unmanned Aerial Systems (UAS) test sites. Provide engineering, programmatic, range operations, and technical expertise in support of the testing and research objectives of the Federal Aviation Administration (FAA) with the intent to safely integrate unmanned aircraft into the National Airspace System (NAS).'}]
,[{name: 'Title', value: 'USMC CSP CBRN SPT (11001)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '11001'},{name: 'ProjectManager', value: 'john.waller'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CBRNE Consequence Management (10917)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10917'},{name: 'ProjectManager', value: 'joan.nicoli'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'RDECOM'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'joan.nicoli'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'COSMIC NCR - IADS - 10315.G05'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10315'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'Apache Programmatic Spt - 10880.001'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10880'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '4;#FFP LOE'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'FMS Apache - 10057.057'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10057'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'The Camber staff has supported the International Apache Office, within the Apache Project Office, continuously over the past 15 years, providing program management, systems engineering, sustainment planning and execution for the world-wide Apache fleet consisting of 14 individual active country programs.  During the FMS planning stage, analysis of alternatives to meet the country operational and budgetary goals are evaluated, and the development and integration of unique capabilities are presented with alternatives for country consideration.  Drafts for the development of a total package to establish a full operational capability is conducted and merged with full pricing and associated schedules.  Upon, security assistance review and country acceptance, the Camber staff executes the FMS case with coordination and contracting actions to ensure cost, schedule, quality and performance documented is obtained.        '}]
,[{name: 'Title', value: 'Ft. Rucker Spt - 10057.058'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10057'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'The objective of this task order is to provide on-site technical and analytical support to the Program Executive Office (PEO) Aviation, the Concept and Requirements Directorate, (CRD), Ft Rucker AL, The U.S. Army Aviation Center  of Excellence (USAACE), in support of the TRADOC Capability Managers (TCMs),  Aviation Project Management Offices (PMOs) for Apache Attack Helicopter (AAH), Cargo Helicopter and the Product Manager for Aviation Ground Support Equipment (AGSE) in the Aviation Systems PMO; and to provide on-site support for PEO-AVN Headquarters in Huntsville, AL. Technical support of these major Army weapons systems, TRADOC Capability Manager (TCM-R/A, TCM-Lift/Cargo, TCM Unmanned Aerial Systems (UAS) and PM AGSE requires extensive and diverse technical expertise and short term analytical technical support for the National Personnel Security System (NSPS) training program. This also includes support for the Objective Force, Future Combat Systems, and participation in Initial Operational Test and Evaluation (IOT&E) evaluations, Limited User Test (LUTs), Advanced Warfighting Experiments (AWEs) and Advanced Concepts and Technical Demonstrations (ACTDs). Both the Apache and Cargo weapons systems have been fielded in significant number and are undergoing performance, durability and quality engineering changes based upon its fielded performance. AGSE is fielded everywhere aviation is based. It will also provide some administrative support for Headquarters, PEO-AVN.  '}]
,[{name: 'Title', value: 'Apache Sensors - 10957.017'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10957'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'BFT Wharehouse Spt - 10901'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10901'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'MAE (Med Alt Endurance) - 10557.020'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10557'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'PM Cargo - 10931.004'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10931'},{name: 'ProjectManager', value: 'john.brooks'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'C4ISR TRAINING PRODUCTS AND RELATED SERVICES SUPPORT '},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'keith.battle'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'SEAPORT-E INTGR TRNS SYS ENG - 10835.0006/10917.0002'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10835/10918'},{name: 'ProjectManager', value: 'kimberly.marshall'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '5;#CPFF LOE'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'Airbus D&S Satellite Programs'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '83259'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: '24;#Airbus'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'PROGRAM MANAGEMENT
Provide overall program manager services to manage satellite programs seeking NSA endorsement of the Committee on National Security Systems Policy 12 (CNSSP 12) and requirements.
PROCUREMENT
Obtain U.S. export license for, procure and ship encryption ground equipment, which can be any combination of MYK-14 Centurion replacement, KIV-7MC (MYK-15A Caribou unit replacement), CDU-100 or other NSA-approved equipment
NATIONAL SECURITY AGENCY (NSA) PROGRAM SUPPORT
Coordinate, prepare and submit the necessary documentation with the NSA on behalf of customer to obtain support and approval for the commercial satellite program.  
This documentation includes Memorandum of Agreement (MOA), Program Cryptographic Requirements Document (PCRD) and all Communications Security Plans (CSPs) authorizing and detailing the receipt, security and operational use requirements of the U.S. Controlled Cryptographic Items used in support the satellite programs over their  anticipated operational life
TECHNICAL ASSISTANCE AGREEMENT (TAA)
Prepare the TAA, coordinate with all required agencies, and submit the TAA application package and supporting documentation to the Department of State (DoS).  Upon approval, Camber will prepare and submit required DoS license applications and supporting documentation..
SECURITY SUPPORT 
Quarterly Security Assessments; Routine Annual Re-Keying Visits; Emergency Call-Out Security Visits; Administrative COMSEC Support Services; & Additional COMSEC Support Services
PROGRAM COMSEC COORDINATION
Coordinate all COMSEC support activities with the NSA, equipment manufacturers and the Space COMSEC custodian supporting development of the satellite programs.
INTERFACE TEST SUPPORT
Support any other U.S. COMSEC Custodian(s) involved in the Satellite Programs to ensure the appropriate security resources and measures are in place to support scheduled SCC satellite integration tests during the satellite manufacturing process.
'}]
,[{name: 'Title', value: 'Brigade Modernization Command - 10979.001'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10979'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'EUTELSAT Satellite Program - 10772'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10772'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'INMARSAT Satellite Programs - 83258'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '83258'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'NORTHCOM Training & Exercise Spt - 10788'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10788'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'LCMC Cost Analysis Spt - 10466.120'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10466'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'Cost analysis, analytical and technical services and products for the TACOM Cost and Systems Analysis (C&SA) office. Technomics provides services in the areas of cost, economic, and technical analysis of major weapon system programs of the Department of Defense. These services include cost, economic, and technical analysis for combat support  and ground combat weapon systems, information management systems, as well as associated acquisition/financial management reporting. This task became much larger and complex on the administrative side than was anticipated. Once we adapted our up-front approach for processing each subtask request, the execution phase flowed nicely without any issues. The customer was pleased with our quality of product/services, schedule compliance, cost control, and business relations.'}]
,[{name: 'Title', value: 'AETC OPS TRAINING - 10761'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10761'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: '15;#USAF'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'The purpose of this task order is to provide Operations Training Analysis Support Services to the Requirements & Resources Division, Operations Directorate, at Headquarters Air Education and Training Command (HQ AETC), Randolph AFB, TX. The support is to provide contract support to ensure adequate resources are planned for, programmed for, and budgeted for all AETC flying and technical training activities. The contract shall supply two positions. This contract will provide on-site support of AETC's mission by providing analysis, assessment and management associated with the technical and flying training funding activities. To address the tasking identified above, HQ AETC is requesting necessary assessment, analysis, and database management services to support HQ AETC's Budget and Programs Branch. In providing this support, the contractor shall interface with relevant members of the HQ AETC staff, other USAF major commands'}]
,[{name: 'Title', value: 'HERCULES FSR SUPPORT - 10631'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10631'},{name: 'ProjectManager', value: 'kirk.davis'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'The HERCULES Support Task provided to BAE (UDLP) and the government the required experience to efficiently and effectively deprocess, issue and train gaining units on the M88A2 tank retriever.  The government had fielded an all military team but due to the constant turnover of personnel and their lack of hands on experience the Customer PM HBCT transitioned to the current model of long term civilian contractor team.  This also enables a closer relationship between the OEM and the fielding team.'}]
,[{name: 'Title', value: 'JUPITR LOGISTICS SUPPORT'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.anderson'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'AMSO Service Support II - 10941'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10941'},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'TRAINING SYSTEMS SW (LOCKHEED) - 10838'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10838'},{name: 'ProjectManager', value: 'leonor.montero'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '5;#CPFF LOE'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'NETC - (10775/11061/11047)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10775/11061/11047'},{name: 'ProjectManager', value: 'mary.shambora'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'USAACE Air Traffic Control - 11105'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11105'},{name: 'ProjectManager', value: 'mary.shambora'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'Anti Access Area Den - 11021 (C12947)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11021'},{name: 'ProjectManager', value: 'matthew.oconnor'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'USPTO OPIM (1011022)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'denise.mcminn'},{name: 'Customer', value: '21;#USPTO'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Project Management (business analysis and oversight).  AGILE SME, SLDC Artifact Collection
'}]
,[{name: 'Title', value: 'USPTO SIRA Support (1010984)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'denise.mcminn'},{name: 'Customer', value: '21;#USPTO'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'USPS Engineering Helpdesk (1011004)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'jared.meylan'},{name: 'Customer', value: '20;#USPS'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Provide hardware and software technical support for about 12,000 DSS and 4,200 PASS machines
7 Day support including most holidays for about 11,500 Postal Delivery Units 
Analyze and recovery of any missing Arrival At Unit scans
FTE - 15
'}]
,[{name: 'Title', value: 'USPS OIG Support (1010944)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'jared.meylan'},{name: 'Customer', value: '20;#USPS'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'USPS SEDS (1010972)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'jared.meylan'},{name: 'Customer', value: '20;#USPS'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Broad range of engineering and information technology business needs for multiple USPS organizations
Support includes system planning and analysis, application design, development, testing, deployment and maintenance, database management, business analytics and reporting, help desk services, staff augmentation and professional services, program / project management, system design and architecture, systems software support and monitoring, and network engineering
IMSG supports five main USPS organizations: (i) Mail Entry and Payment Technology, (ii) Engineering, (iii) Corporate Reporting, (iv) Office of the Inspector General (OIG) and (v) Global Business
Supported USPS for over 20 years
215+ employees
'}]
,[{name: 'Title', value: 'IAM (82117)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '82117'},{name: 'ProjectManager', value: 'michael.buscher'},{name: 'Customer', value: '26;#Classified'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'The scope of work is providing identity, biometric and biographic intelligence analysis for a classified USG Customer at the TS/SCI level.'}]
,[{name: 'Title', value: 'Data Sales (Quartz/Quigley/Quiznos)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'michael.buscher'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'KWEB (10869)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10869'},{name: 'ProjectManager', value: 'michael.buscher'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'Two Pair (82121)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '82121'},{name: 'ProjectManager', value: 'michael.buscher'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'FED CTE (1011027)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: ''},{name: 'Customer', value: '2;#DHS'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Cyber Security Training (Instructor-led), Interactive Multi-media (virtual world), Project Management
'}]
,[{name: 'Title', value: 'ARMY MOBILE INSTRUMENTED TRAINING SYSTEM (AMITS)--STOC II - 10965'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10965'},{name: 'ProjectManager', value: 'paschal.aquino'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CRANE JXT SOFTWARE SPT - 10835.FC01'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10835'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: '19;#USN'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: 'Software Engineering, Development, Programming and Network Support.  This task consists of Network design, implementation, troubleshooting, analysis, and maintenance of G-BOSS’s network. This also encompasses the software development required to integrate Cursor on Target (CoT) in to the G-BOSS 2.0 Software Baseline (EBRISS 4.0).  CoT is an XML schema for time-sensitive position information such as spot reporting, blue force tracking, and relocation requests.  Time-sensitive information that specifies the “what, when and where” information is considered critical, especially in asymmetric warfare arenas such as Iraq and Afghanistan.  Agility and responsiveness are the keys to military superiority.  The CoT event data model defines a terse XML schema and sub-schema extensions for exchanging time-sensitive positions of moving objects. The schemas are arranged in an object model with the intention of simplifying application development.  Rudimentary entities, such as event, detail, and points with limited attributes, are sufficient for almost 90 percent of all information transfers needed for battle management.  These entities can be further extended to provide additional details where necessary.  This allows smarter applications to exchange information beyond these rudimentary objects.  There will be two primary software development pieces.  The first piece will involve the production of an EBRISS driver to interface with CoT compliant external interfaces and all necessary modifications to the EBRISS server.  The second piece is the possible addition of a GUI widget to the EBRISS Client and all GUI control and visualization support for UAV Platform and Sensor Point of Interest CoT messages.  The final element of this task would include any necessary EBRISS Client infrastructure changes to communicate with the server.'}]
,[{name: 'Title', value: 'AFNIC CDSO '},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10786/10950'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'Rock Island - 11099'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11099'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'US Air Force Medical Modeling & Simulation Training (AFMMAST) - 10919'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10919'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'AFNET '},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10801'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: '15;#USAF'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'Camber provides services in Customer Relationship Management, Certification and Accreditation Project Management, Network Validation, Network Engineering, and Network Architecture in support of the Air Force, Air Force Space Command (AFSPC), and the 24th Air Force Cyber Command (AFCYBER) missions. Specific services provided by Camber include:
 Providing test engineering services to facilitate integration and validation testing of systems, application, and products in the Representative AFNET Validation Environment (RAVE) or other testing environments.
 Providing necessary technical research and analysis necessary to validate the performance of products, applications, and solutions through security, compatibility, interoperability, and integration testing with core services and common/standard infrastructure and integrating new capabilities onto the AFNET and closed networks.
 Supporting the Air Force Network Integration Center (AFNIC) by providing consultation with program managers and their staff on Information Assurance Strategy throughout the system life cycle.
 Performing Commercial-Off-the-Shelf (COTS)/Government-Off-the-Shelf (GOTS) vulnerability assessments to evaluate the risk of operating the desktop and Web-based products and application on the AFNET.
 Providing support and analysis on operations with processing COTS/GOTS assessment requests from the Air Force Space Command IT request Integrated Product Team, AFNET, and system Information Assurance Managers (IAMs).
 Developing metrics and analysis to track and assess certification and accreditation status of various components of the AFNET. These metrics are based on information collected via SharePoint databases during the processing of system and software certification processes.
 Providing Customer Relationship Management (CRM) support to assist the AFNIC in their customer service and support operations, to include developing metrics, providing trend analysis, generating reports and providing recommendations/solutions to resolve gaps/shortfalls from adversely affecting core services.
 Configuring and maintaining a Microsoft SharePoint based solutions supporting content management, customized workflows, and CRM site administration.
 Providing technical research and analysis necessary to obtain engineering, technical, and procedural documentation for validating products, applications, and solutions through testing with AFNET core services and common/standard infrastructure and integrating new hardware and software capabilities onto the AFNET and closed networks.
 Conducting assessments of information systems requesting access to the enterprise network to ensure integration and cyber security requirements are met, to include preparing risk assessment documentation in accordance with established criteria and comply with standard operating procedures as established by the functional area work center.
 Providing production management support, to include:  receiving support requests from customers, assess completeness of the request, and assign documents to appropriate technical assessors based upon standard operating procedures.
 Conducting analysis and engineering studies of Air Force network requirements & architecture documents, to include reviewing and analyzing requirements & architectures documents; assessing documents for completeness & integration issues.
 Conducting network engineering reviews of IT destined for connection to AF networks, to include providing recommendations to customers to support the development of systems and products that meet connection requirements as required.
'}]
,[{name: 'Title', value: 'NETCENTS CMOS OLVIMS (10951)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10951'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: '15;#USAF'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'Camber Corporation, as a subcontractor to DSD Laboratories, provides technical support to the Air Force’s Cargo Movement Operations System (CMOS) and the On-Line Vehicle Interactive Management System (OLVIMS).  
CMOS is an integrated system consisting of computer hardware, software, and networking equipment that facilitates effective planning, documentation and management of outbound and inbound cargo and passengers.  It also facilitates the planning, scheduling, and monitoring the execution of transportation activities in support of deploying forces and forces returning from deployment.  With systems in operation at 360 US Air Force, US Army, US Navy, US Marine Corps, and National Security Agency sites, CMOS provides these customers and the warfighters they support with an end-to-end distribution capability and real time in-transit visibility during all passenger and cargo movements. As part of the services we provide in support of CMOS, we are also heavily engaged in implementing and activating the system at more than 30 additional US Army sites and 140 new Navy sites.  Specific services provided by Camber include:
 Providing engineering assessments and input during all phases of CMOS software development including Define Need, Design, Build & Test, and Release & Support 
 Serving as the alternate team lead for all CMOS engineering/technical support personnel
 Serving as Primary POC for all CMOS I2P (Industry Information Processor) Carrier Module loads in both the test and production environment
 Serving as Primary POC for all Technical Refresh initiatives of CMOS hardware housed at DISA
 Serving as technical liaison to all support organizations outside the PMO
 Serving as CMOS Architecture lead
 Providing engineering assessments and input to the CMOS Security Engineer for CMOS security maintenance and requirements 
 Providing engineering support for test activities related to all CMOS software releases
 Providing Operations and Database engineering support services for the DISA production environment and the PMO
 Serving as lead for the CMOS Contingency of Operations Plan (COOP)
 Serving as Engineering lead for CMOS Army Implementation
OLVIMS, is in use at 325 Air Force installations and is designed to provide full spectrum automated support to the Air Force’s vehicle fleet.  This system encompasses nearly all facets of vehicle maintenance, fleet management, driver licensing, War Readiness Vehicles, vehicle rotations and recalls, vehicle requirements and authorizations, and warranty of vehicles, parts, and contracted maintenance.  It also gathers, tracks and reports on serviceability status, labor time accounting activities, vehicle dispatch requirements, parts requirements and consumption data. In addition, it collects and provides critical planning information such as fuel quantities consumed along with the associated cost, overall fleet analysis; and vehicle warranty information. Camber’s engineers and technicians play a key role in the sustainment, maintenance, modification, development, test, integration, and implementation of OLVIMS (both Web-based and PC-based).  We are intimately familiar with and heavily involved with the OLVIMS software, hardware and the methods it uses for communication.  As maintainers of this system, our engineers focus their efforts on activities that reduce duplication across systems, and providing up-to-date data to the Air Staff and Major Commands.  We also modify legacy applications and database code to provide new or enhanced functionality or changing application or database code to provide technical or software refresh to maintain compatibility in the Air Force enterprise computing environment.  In addition, our engineers provide expertise in data management, quality assurance, systems engineering, problem resolution, software testing, configuration management, field assistance, functional software analysis and software application training.
'}]
,[{name: 'Title', value: 'DISA FSO (10982)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10982'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'CRANE MEW Towed Decoy - 10832.FC01'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10832'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: '19;#USN'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Decoy Launching System MK 36 (Super Rapid Blooming Offboard Countermeasures) sustainment/disposal support. 
Decoy Launching System MK 53 (NULKA) system acquisition and sustainment/disposal support.
Decoy Launching System MK 59 Passive Off-Board Decoy and Launching System (dlf3b) systems acquisition support.
1. Overview – describe the customer and provide a brief background of the requirements (i.e., overall scope of work).
General Naval Weapon Systems engineering and logistics support.
'}]
,[{name: 'Title', value: 'CRANE JX Admin Spt Svcs- 10948'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10948'},{name: 'ProjectManager', value: 'patricia.lewis'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '6;#T&M + Fee'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'JPEO OPETS'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'paul.panozzo'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'DCRF (10863.009)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10863'},{name: 'ProjectManager', value: 'peter.upson'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'FFX CAD2CAD (1010973)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'nandakumar.rajagopal'},{name: 'Customer', value: '6;#Fairfax County'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'IT Services, Data Exchange, Change Advisory Board support'}]
,[{name: 'Title', value: 'Waterfront Team Trn Spt (10850.0041/11081.00)'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10850'},{name: 'ProjectManager', value: 'reginald.briggs'},{name: 'Customer', value: '19;#USN'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Provide Waterfront Team and Maintenance Training support and Management
Support at Fleet Concentration Areas (FCA) for the Center for Surface Combat Systems (CSCS) domain. The CSCS consists of the Command Staff located at Dahlgren, VA, CSCS Units, Sites and Detachments World-wide. 
Training consists of waterfront training support for Advanced Warfare Training
(AWT), which includes Integrated Air and Missile Defense (IAMD), Ballistic Missile Defense
(BMD), Ship Self Defense System (SSDS), and Anti-Submarine Warfare (ASW).

Camber provides four full time employees as sub under General Dynamics (GDIT) contract. Three work at a government site in San Diego, CA and the other at a government facility in Pearl Harbor, HI. All are retired Navy veterans with over 106 years of combined naval combat systems experience. They provide a wide range of individual and watchteam training in both the classroom and shipboard environments.
'}]
,[{name: 'Title', value: 'GAO Phoenix III (1001945)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '8;#GAO'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: 'IT Services, Infrastructure Support, LAN WAN administration'}]
,[{name: 'Title', value: 'Avaya Engineering Support (1010952.0002)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: '1010952'},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '25;#Avaya'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'DHS HSIN Outreach/Arc Aspicio (1001941)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: '1001941'},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '2;#DHS'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'AOR Project Management, Outreach, SharePoint Administration'}]
,[{name: 'Title', value: 'Fairfax County Schools OFNS (1010969)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '6;#Fairfax County'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'Finance Systems Development and Control Systems'}]
,[{name: 'Title', value: 'FEMA PBX (1010952.0003)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '7;#FEMA'},{name: 'ContractType', value: '1;#FFP'},{name: 'CategoryDescription', value: 'IT Services, Infrastructure Support, Avaya Engineer'}]
,[{name: 'Title', value: 'Department of Education (1001935)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: '1001935'},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '3;#DoEd'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Provide comprehensive Web Support Services to the Department of Education for the Department’s public-facing internet and intranet Scope of services includes the following areas:  project management, system engineering and design support, software/web development support, system development support, data analysis, quality and management support, training and documentation support, systems security and information assurance support, and emerging technologies support. 
Provide effective connectED (Intranet portal) development, enhancements, operations, and maintenance, including Enterprise site, sub-sites, and Inside ED blog site
Effective development, enhancements, operations, and maintenance for additional externally-facing and internally-facing web applications 
4 FTEs located at ED in DC
'}]
,[{name: 'Title', value: 'DOJ/ATF Network Mgmt Svcs (1011039)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '4;#DOJ/ATF'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Network Support Services, Campus Work Station Support '}]
,[{name: 'Title', value: 'Fairfax County Courts CARS (1001727/1011051)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '6;#Fairfax County'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'Camber team supports FCC’s CARS System, which in turn serves the general public through web based document indexing, storage & retrieval of court documents including land records, probate, marriage licenses, judgments  offices etc.
CARS brings significant advantages to the automation of recording images by supplying a workflow engine that captures, enhances, processes, and records documents.
CARS was designed to produce a rapid return on investment by eliminating maintenance costs for microfilm/microfiche equipment, reducing both labor costs and space requirements
Design, development and enhancements for the Fairfax County Circuit Courts Automated Recording System (CARS) including Courts automated billing System (CABS), Electronic Filing System (EFS) and Courts Public Access Network (CPAN), Court Document Recording System (CDRS)
'}]
,[{name: 'Title', value: 'NSD SE&I SUPPORT (1010912)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '10;#NSD'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'OPP INFO Systems (1001948)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '11;#OPP'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'TSA IHOPP/Lockheed (1001805/1011092)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '13;#TSA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'IT Services, SME - HR Case Management
'}]
,[{name: 'Title', value: 'USAID OFDA (1010999)'},{name: 'BusinessUnit', value: '1;#DMIT'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'lee.rench'},{name: 'Customer', value: '16;#USAID'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'USARC (10863.014)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10863'},{name: 'ProjectManager', value: 'robert.defebbo'},{name: 'Customer', value: '17;#USAR'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'Performs logistic integration and life-cycle management (LCM) activities for CBRNE Commercial Off the Shelf (COTS) including maintenance, repair, calibration and OEM warranty services, as well as supply and sustainment. Conduct formal certification training for emergency responders in accordance with CFR29-1910.120q.'}]
,[{name: 'Title', value: 'NAVY NIC OCO (10867.010)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10867'},{name: 'ProjectManager', value: 'robert.defebbo'},{name: 'Customer', value: '19;#USN'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'This Logistics Domain defines the program, engineering, and technical support services required for the Joint Program Executive Office for Chemical and Biological Defense (JPEO-CBD) and all the Joint Project Management Offices (JPMOs) which report directly to the JPEO-CBD.  JPEO-CBD manages a dynamic and diverse portfolio of critical warfighting capabilities that require cohesive and innovative total life cycle systems management approaches to rapidly respond to the needs of the Force balanced by affordable sustainment strategies.  Due to the schedule-driven nature and criticality of solutions to the Warfighter, a cohesive strategy for rapid assessments, evaluation, fielding, New Equipment Training (NET), sustainment, and continuous product improvement activities are essential to the JPEO-CBD support strategy to its customers.  This domain establishes the requirement to provide Systems Engineer, Configuration Management Specialist, Risk Management Specialist, Science and Technology Analyst, Architecture Support, Communications Analyst and Test Analyst support, as required, to assist the JPEO-CBD as the Total Life cycle Systems Manager for the Chemical and Biological Defense Programs (CBDPs) within the Department of Defense (DoD).'}]
,[{name: 'Title', value: '20TH/48TH CBRN'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'robert.defebbo'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'C2CRE-B'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'robert.defebbo'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'NAVY CBRN SUST'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: ''},{name: 'ProjectManager', value: 'robert.defebbo'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'ONI (10866.025)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10866'},{name: 'ProjectManager', value: 'ronald.brandon'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'DASA(R&T) - 11043'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '11043'},{name: 'ProjectManager', value: 'russ.mcdonald'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: ''}]
,[{name: 'Title', value: 'MDA PRIDE - 10661.004'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10661'},{name: 'ProjectManager', value: 'russ.mcdonald'},{name: 'Customer', value: ';#'},{name: 'ContractType', value: '3;#CPFF'},{name: 'CategoryDescription', value: 'Camber is a subcontractor on the ESC Federal, Inc. team supporting the Missile Defense Agency (MDA) Agency Business Operations Directorate in implementing, integrating, maintaining, and continually improving MDA financial systems and processes. 
This support is required for the Director for Agency Operations (DO), Director of Budget (DOB), and is located in Huntsville, AL. 
All Camber employees hold Secret clearances and all IAT level I and II personnel meet DoD 8570.01-M certifications.  
Camber support focuses on software application development, web portal and special software support, software project management, user training and support, business process and requirement development, financial systems integration, and database administration.    
This task order supports the MDA DOBS organization in the delivery of a full range of integrated financial systems. These business systems support the utilization of the Plan, Program, Budget and Execute (PPBE) process, Defense Agency Initiatives (DAI) modules, Program Resource Intranet Database Environment (PRIDE), and legacy systems Information Management Program Activity Control Tool (IMPACT) and Standard Operation and Maintenance Army Research and Development System (SOMARDS), and enables quality system development, maintenance, and integration.
'}]
,[{name: 'Title', value: 'AMCOM LOGSA LITE'},{name: 'BusinessUnit', value: '2;#TCE'},{name: 'ProjectNumber', value: '10823'},{name: 'ProjectManager', value: 'russ.mcdonald'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: '2;#T&M'},{name: 'CategoryDescription', value: 'As a member of Team IBM, Camber provides the United States Army Logistics Support Activity (LOGSA) high quality, efficient and effective Information Technology (IT) services that include software development, database management and analysis, application integration, business case analysis, IT project management, and systems operations and maintenance. Camber currently employs a full time staff of 33information systems professionals on site to LOGSA at Redstone Arsenal. Our team assists LOGSA in supporting the Logistics Information Warehouse (LIW), which has been designated as the official authoritative repository for Army logistics data.  LOGSA and its LIW suite of products and services provide the Army community with vital logistics data necessary for the planning, conduct, and sustainment of war fighting capability worldwide.  Specific areas of Camber support are as follows:
Project Management and Planning – We are responsible for planning, executing, controlling, reporting LOGSA software projects following ITIL, CMMI, and DoD standards processes and procedures. Our staff includes Project Planning Managers in support of Project Team Leads.
Database Administration, Analysis, and Programming – We support a broad spectrum of database and portal operations including; 
• Systems development life cycle support for Oracle Portal, JIRA, and OBIEE 11g.  This suite hosts the LIW Portal and requires heavy Web Logic administration. 
• Ensure optimal application uptime by efficient coordination of system maintenance. 
• Actively support and troubleshoot large scale, mission critical, high volume production systems.
• Develop and maintain extensive PL/SQL packages that interface with front-end Web based Java applications. These packages utilize Oracle functions, collections, Dynamic SQL, reference cursors and exception handling.
• Actively participate in application design, database design, schema layout and data loading. Verify accuracy and completeness of systems by preparing sample data and testing.
• Develop design and performance requirements, 
• Deploy new or modified database objects into database frequently.
• Implemented Security Controls as outlined by DISA Security Implementation Guides.
• Monitored database growth and work with Storage Administrators 
Application Software Developers and Analysts - Our software application developers and analysts support LOGSA’s migration, consolidation and modernization of custom, web –based logistics management applications. This includes design, development, testing, and implementation of the dozens of applications that compose the Logistics Information Warehouse (LIW) web portal. This portal provides for world-wide user access to many of the Army’s logistics applications and utilizes a variety of technologies including ;   Oracle Business Intelligence (BI), Oracle Web Logic, Fusion middleware, Java, J2EE, Java Sever Faces (JSF), Spring  Cold Fusion, PHP, Perl, HTML, JavaScript, AJAX, JSON, XML, ASP, PL/SQL, and Oracle 10/11 databases.
Business Systems Analysts- Our Business Systems Analysts are thoroughly familiar with LOGSA’s Logistics Information Warehouse (LIW) structure, products, and content, and have a detailed understanding of LOGSA development processes and tools.  We review and analyze business information to automate, document, and streamline their business procedures and processes. Following the LOGSA System Engineering Process (SEP),  we design workflows and processes, build Unified Modeling Language -based, requirement definition packages using the Contour application, Power Designer modeling tool, and Enterprise Architect modeling tool. 
We are also responsible for the daily function and updates of LOGSA’s critical databases and programming changes to UNIX scripts, and SQL to keep systems up to date and running. We are responsible for keeping current daily FORCE structure up to date and maintenance of historical Readiness data.
CTASC System Administrators - Provide 24x7 systems administration support of the Standard Army Retail Supply System (SARSS) at the Corps Theater Automated Data Processing Service Center (CTASC). Tasks include HP-Unix operating system administration, INFORMIX database administration, and Windows Server 2008 administration. Other duties include Access Control List (ACL) maintenance on a CISCO Firewall Services Module, end user support, account maintenance, network troubleshooting, system and secure file transfer protocol (SFTP) troubleshooting, building and maintaining routing tables, monitoring and maintaining data flow to supported SARSS-1 sites, daily/monthly system and database backups, push and verify data to the disaster recovery site in support of our Continuity of Operations Procedures (COOP). 
Information Assurance (HBSS Administration) - Responsible for installation, configuration, integration, and maintenance of HBSS components and deployment of Agent modules and approved policies. Perform troubleshooting of HBSS components and applications. Maintain the latest HBSS configuration to address known exploits using the Host Intrusion Prevention System (HIPS). Monitor the HBSS for alerts. Conduct analysis of malicious events and known exploits/vulnerabilities for the creation of custom signature rule sets for the accompanying modules, as necessary.  
Documentation Specialists - Responsible for preparing contract CDRLs and maintaining systems and operations documentation, procedures, and methods including user manuals and reference manuals. Provide and coordinate special documentation services as required. Provide administrative assistance duties as required.
'}]
,[{name: 'Title', value: 'ADM (10614)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10614'},{name: 'ProjectManager', value: 'timothy.goodwin'},{name: 'Customer', value: '14;#USA'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'Camber provided the ECBC Engineering Directorate’s ADM Division with the following:  project management (including requirements definition); requirements analysis; project status reporting; market research; technical support; detailed component and systems design and engineering (including engineering packages, 3D modeling, rapid prototyping, fabrication and manufacturing); systems integration; fielding; and logistical support/sustainment across the wide spectrum of tasks for which the ADM Division is responsible. 
Our highly skilled and experienced technicians performed a number of engineering functions, including; Computer Aided Design (CAD), 3D modeling, and American National Standards Institute (ANSI) and International Organization for Standardization (ISO) compliant drawings for multiple complex CBRNe requirements for ECBC and its customers. This support ranged from mechanical design and design analysis through fabricating and manufacturing production items using the latest Computer Aided Engineering (CAE) software, equipment, and processes. 
We also supported the day-to-day operations of ADM shops and facilities in a number of areas, including supply operations, market research, material handling, equipment maintenance, and the skilled and safe operation of complex manufacturing equipment, e.g. Computer Numeric Control (CNC)/Conventional Milling and Turning, Electrical Discharge Machining, Plastic Injection Molding, Vacuum Forming, and the forming and punching of sheet metal and other materials. As a priority, we made sure operations always conformed to all applicable local shop safety standards, ECBC and Army safety requirements, and Occupational Safety and Health Administration (OSHA) directives. 
All parts and components were manufactured in accordance with Army specifications, ANSI standards, and local quality control and inspection requirements. Camber fabricated parts, tools, and fixtures for small-scale to full-scale production requirements. Camber also provided post-fabrication/manufacturing support, including fielding, training, and logistical sustainment assistance in support of warfighters worldwide. This often required short notice and rapid response travel to CONUS and OCONUS locations. Our experience supporting ADM with design, development, manufacturing, integration, training, fielding, and life cycle sustainment reaffirmed our position as a forward leaning and highly successful engineering and technical services provider.
ADM’s customers have a vast array of projects, used in settings ranging from the battlefield to the chemical testing lab requiring unique materials. ADM offers its customers the ability to work with a wide spectrum of materials, including ferrous, nonferrous, plastic, composite, and wooden materials. Camber operates various manufacturing equipment and processes, such as Computer Numeric Controlled (CNC), conventional mills and lathes, wire electric discharge machining, injection molding, vacuum forming, sheet metal shears and brakes, water jet cutters, saws, and sanders to produce products or transportation packaging. 
We understand development of first article devices and proof-of-concept systems often require design adjustments during manufacture, and our engineers and technicians are highly skilled at utilizing AutoCAD, SolidWorks, and Sigmanest applications to modify CAM and CNC designs on the fly, thus making sure the end result was a fully functioning product.
'}]
,[{name: 'Title', value: 'ESSO-Silentroar (10879/10864)'},{name: 'BusinessUnit', value: '3;#P&I'},{name: 'ProjectNumber', value: '10879'},{name: 'ProjectManager', value: 'tim.mcconaghy'},{name: 'Customer', value: '9;#NSA'},{name: 'ContractType', value: ';#'},{name: 'CategoryDescription', value: 'The purpose of this contract was to provide subject matter experts (SMEs) possessing military mission and technologic expertise to aid SILENTROAR in fulfilling the National Security Agency (NSA)/Central Security Service (CSS) goal of fully developing and integrating the extended cryptologic enterprise to provide dominant Signals Intelligence (SIGINT) capabilities to our US Military and its partners. 
This contract also provided SMEs in coordinating and developing cryptologic support plans in support of Combatant Command Concept and Operational plans. It also provides SMEs in the planning and execution of cryptologic support to major combatant commands exercises.
Drove NSA/CSS and the Services to “organize, train, and equip” through a coordinated strategy to shape the enterprise into a seamless, responsive, agile, cryptologic system; received and understood warfighter capability requirements, dissected them, and then ensured the right NSA/CSS or Service organization(s) were assigned to resolve the issue; managed the solution process end-to-end, delivering a complete solution to the warfighter. The solution included hardware, assistance in incorporating a capability on the battlefield, providing the necessary training, and ensuring logistics sustainability for that capability. The SILENTROAR was charged with:
• Facilitating the coordination of cross-functional Cryptologic doctrine, organization, training, leadership development, materiel, personnel and facilities (DOTLMPF) issues for the Unified Cryptologic System (UCS)
• Serving as the authoritative spokesperson for all activities related to tactical SIGINT system planning, development, and programmatic oversight
• Technical Oversight Authority for Tactical SIGINT Investment program. Providing comprehensive program management of Military Intelligence Program (MIP), formerly the Defense Cryptologic Program (DCP), and NSA/CSS portion of the Defense Airborne Reconnaissance Program (DARP)
• Cross-walking technology between cryptologic development programs
• Leveraging the SIGINT Enterprise to support urgent tactical DOTLMPF SIGINT requirements
• Developing and integrating joint and net-centric operational concepts and solutions for the Tactical SIGINT Community to achieve a networked, integrated and self-synchronizing Intelligence, Surveillance, Reconnaissance (ISR) enterprise
• Program management of the Tactical SIGINT Technology (TST) program, to include technical, financial, and administrative responsibilities
• Managing, integrating, and where applicable, leading NSA/CSS participation in Military Exploitation of Reconnaissance and Intelligence Technology (MERIT), Tactical Exploitation of National Capabilities (TENCAP), and Advanced Concept Technology Demonstrations/Joint Capability Technology Demonstrations (ACTD/JCTD) Programs
• Facilitating the migration of advanced technologies into tactical systems
• Developing and executing integration and interoperability proofs of concept and prototypes, providing end of test and evaluation reports to document these efforts
• Providing cryptologic support to external exercises, and planning and executing exercises in support of internal NSA/CSS training objectives.
'}]
]












