define([
    "./jsom2json"
], function (
    j2j
) {
    var util = {

        loadProjects: function(args){
            var siteUrl = args.siteUrl
            var listName = args.listName

            projects.forEach(function(project){
                var spdata = {}
                
                spdata.Title = project.projectName
                spdata.ProjectDescription = project.projectDescription
                spdata.BusinessUnit = project.businessUnit
                spdata.ProjectNumber = project.projectNumber
                spdata.ProjectManager = project.projectManager
                spdata.Customer = project.customer
                spdata.CustomerDetail = project.customerDetail
                spdata.ContractType = project.contractType
                spdata.PlaceofPerformance = project.placeOfPerformance
                spdata.PrimeContractor = project.primeContractor
                spdata.PrimeContractorName = project.primeContractorName
                spdata.SecurityClearedWork = project.securityClearedWork
                spdata.SecuritySCIF = project.securitySCIF
                spdata.ContractValue = project.contractValue
        
                j2j.modifyListItem(siteUrl, listName, project.projectName, spdata)
            })

        }

    },
    projects = [
        {"projectName":"1001935","projectDescription":"Provide comprehensive Web Support Services to the Department of Education for the Department's public-facing internet and intranet Scope of services includes the following areas:  project management, system engineering and design support, software/web development support, system development support, data analysis, quality and management support, training and documentation support, systems security and information assurance support, and emerging technologies support. Provide effective connectED (Intranet portal) development, enhancements, operations, and maintenance, including Enterprise site, sub-sites, and Inside ED blog siteEffective development, enhancements, operations, and maintenance for additional externally-facing and internally-facing web applications 4 FTEs located at ED in DC","businessUnit":"1;#DMIT","projectNumber":"1001935","projectManager":"Rench, Lee (HII-TSD)","customer":"3;#DoEd","customerDetail":null,"contractType":"1;#CPFF","contractValue":"$3M","practices":[],"placeOfPerformance":"Fairfax, VA","primeContractor":true,"primeContractorName":null,"securityClearedWork":true,"securitySCIF":true,"technicalLead":null},
        {"projectName":"Avaya Engineering Support (1010952.0002)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":"1010952","projectManager":"Rench, Lee (HII-TSD)","customer":"24;#Avaya","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"PTX (11079)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11079","projectManager":"McConaghy, Tim (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NANA (10634)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10634","projectManager":"McConaghy, Tim (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"UMSS - System Execution - 11014.002","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11014","projectManager":"Gill, Thomas (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"SEAPORT-E CDSA ENG SPT - 10835.0007/10917.3011","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10835/10917","projectManager":"Cherry, Anthony (HII-TSD)","customer":null,"customerDetail":null,"contractType":"2;#CPFF LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"EPA","projectDescription":"IT Services, Software and Web Development","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":null,"customer":"5;#EPA","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"RACRS - 10889","projectDescription":"The objective of the Apache SMART program is to perform Modeling and Simulation (M&S) risk reduction activities utilizing the Government-owned Apache Risk and Cost Reduction System (RACRS). Camber has served as an engineering extension of the Apache project office from 2000 to 2015 to assist with the evolution of aircraft modification concepts into solutions that meet the needs of Army Aviators thereby avoiding rework due to misunderstood or loosely defined requirements. In support of this objective, Camber developed, maintains, and operates an Apache laboratory with aircraft software and hardware capabilities for the purposes of prototyping and mission-based evaluations/trials.  Camber engineers also provide project sustainment support to address maintenance, data backup, obsolescence, currency with the fielded aircraft, and upgrade of technology to perpetuate relevancy of the RACRS as a prototyping test bed.  On average, the RACRS program has 8-12 active task orders at all times, each with 9-18 months of duration. The conduct of simulated flight test rehearsals verifies and validates hardware and software upgrades substantially lowering the risk and cost of repetitive flight testing","businessUnit":"2;#TCE","projectNumber":"10889","projectManager":"Budisalich, Scott (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"MDA Enviromental Mgt - 11052","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11052","projectManager":"McDonald, Russ (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"PM Acquisition Business Technology - 10916","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10916","projectManager":"McDonald, Russ (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AFCAP LSS","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Remley, Sean (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"UAE CBRNE Academic Training (10881)","projectDescription":"Camber provides 22 USMC installations worldwide with Contractor Logistics Support (CLS) which includes total asset management for over $50M of CBRNE equipment. We deploy Subject Matter Experts (SMEs) at Continental United States (CONUS) and Outside the Continental United States (OCONUS) Marine Corps locations.  Camber conducts training; acquisition, technical, and engineering support; and supply chain management, to include shelf-life monitoring and configuration management.  We manage inventory, conduct maintenance, store CBRNE equipment, and distribute the equipment to installations as needed.  We provide real-time visibility of all assets program-wide which gives the Headquarters Marine Corps (HQMC) the ability to shift equipment in response to threat situations.  Camber provides total asset management for over 1,900 line items and over 200,000 assets/pieces of CBRNE and First Responder/Receiver equipment.  We also provide training and exercise support, development and implementation of installation CBRNE protection plan annexes in installation incident response plans, and equipment maintenance and sustainment for CBRNE IPP.  CLS also includes management and technical support to the installations as required for Organizational Doctrine, Training, Operations, and related CBRNE and emergency management issues","businessUnit":"3;#P&I","projectNumber":"10881","projectManager":"Tunstall, Stanley (HII-TSD)","customer":"17;#USMC","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Program Spt for Cruise Missle Defense Sys (CMDS) PO - 10234.N01","projectDescription":"Camber provided programmatic support for Project Manager Unmanned Aircraft Systems (UAS), Product Manager (PdM) Medium Altitude Endurance (MAE)/Gray Eagle UAS, PM Tactical Concepts (now PdM Modernization)/Hunter UAS, Improved Gnat (IGNAT) UAS, Warrior A and Warrior Block 0 UAS, PdM Ground Maneuver/Shadow, PdM Small UAS/Raven, PdM Future Combat Systems/four classes of UAS, and PdM Common Systems Integration (CSI). ","businessUnit":"2;#TCE","projectNumber":"10234","projectManager":"McDonald, Russ (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"MDA Site Activation - 10923","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10923","projectManager":"McDonald, Russ (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AO Maintenance of DSO Websites (1001947)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":"1001947","projectManager":"Schmitt, Norma (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"OUSD AT&L - 10977/11026","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10977","projectManager":"Remley, Sean (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FCBRNS/FIRS","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Jeambert, Stacy (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"F-15 CAATS","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Field, Ted (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Joint Force Dev Svcs - 10956.002","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10956","projectManager":"Knight, Terry (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"TSA IHOPP/Lockheed (1001805/1011092)","projectDescription":"IT Services, SME - HR Case Management","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"12;#TSA","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NAVY NIC OCO (10867.010)","projectDescription":"This Logistics Domain defines the program, engineering, and technical support services required for the Joint Program Executive Office for Chemical and Biological Defense (JPEO-CBD) and all the Joint Project Management Offices (JPMOs) which report directly to the JPEO-CBD.  JPEO-CBD manages a dynamic and diverse portfolio of critical warfighting capabilities that require cohesive and innovative total life cycle systems management approaches to rapidly respond to the needs of the Force balanced by affordable sustainment strategies.  Due to the schedule-driven nature and criticality of solutions to the Warfighter, a cohesive strategy for rapid assessments, evaluation, fielding, New Equipment Training (NET), sustainment, and continuous product improvement activities are essential to the JPEO-CBD support strategy to its customers.  This domain establishes the requirement to provide Systems Engineer, Configuration Management Specialist, Risk Management Specialist, Science and Technology Analyst, Architecture Support, Communications Analyst and Test Analyst support, as required, to assist the JPEO-CBD as the Total Life cycle Systems Manager for the Chemical and Biological Defense Programs (CBDPs) within the Department of Defense (DoD).","businessUnit":"3;#P&I","projectNumber":"10867","projectManager":"Defebbo, Robert (HII-TSD)","customer":"18;#USN","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USARC (10863.014)","projectDescription":"Performs logistic integration and life-cycle management (LCM) activities for CBRNE Commercial Off the Shelf (COTS) including maintenance, repair, calibration and OEM warranty services, as well as supply and sustainment. Conduct formal certification training for emergency responders in accordance with CFR29-1910.120q.","businessUnit":"3;#P&I","projectNumber":"10863","projectManager":"Defebbo, Robert (HII-TSD)","customer":"16;#USAR","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USAID OFDA (1010999)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"15;#USAID","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NSD SE&I SUPPORT (1010912)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"10;#NSD","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"OPP INFO Systems (1001948)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"OPP","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"C2CRE-B","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Defebbo, Robert (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ONI (10866.025)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10866","projectManager":"Brandon, Ronald (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"20TH/48TH CBRN","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Defebbo, Robert (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NAVY CBRN SUST","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Defebbo, Robert (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"DASA(R&T) - 11043","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11043","projectManager":"McDonald, Russ (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"DHS HSIN Outreach/Arc Aspicio (1001941)","projectDescription":"AOR Project Management, Outreach, SharePoint Administration","businessUnit":"1;#DMIT","projectNumber":"1001941","projectManager":"Rench, Lee (HII-TSD)","customer":"2;#DHS","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"GAO Phoenix III (1001945)","projectDescription":"IT Services, Infrastructure Support, LAN WAN administration","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"8;#GAO","customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Fairfax County Schools OFNS (1010969)","projectDescription":"Finance Systems Development and Control Systems","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"6;#Fairfax County","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FEMA PBX (1010952.0003)","projectDescription":"IT Services, Infrastructure Support, Avaya Engineer","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"7;#FEMA","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FFX CAD2CAD (1010973)","projectDescription":"IT Services, Data Exchange, Change Advisory Board support","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rajagopal, Nandakumar (HII-TSD)","customer":"6;#Fairfax County","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"IAM (82117)","projectDescription":"The scope of work is providing identity, biometric and biographic intelligence analysis for a classified USG Customer at the TS/SCI level.","businessUnit":"3;#P&I","projectNumber":"82117","projectManager":"Buscher, Michael (HII-TSD)","customer":"25;#Classified","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Avaya Engineering Support (1010952.0002)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":"1010952","projectManager":"Rench, Lee (HII-TSD)","customer":"24;#Avaya","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CRANE JX Admin Spt Svcs- 10948","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10948","projectManager":"Lewis, Patricia (HII-TSD)","customer":null,"customerDetail":null,"contractType":"6;#T&M + Fee","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"JPEO OPETS","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Panozzo, Paul (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"DCRF (10863.009)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10863","projectManager":"Upson, Peter (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ARMY MOBILE INSTRUMENTED TRAINING SYSTEM (AMITS)--STOC II - 10965","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10965","projectManager":"Aquino, Paschal (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Two Pair (82121)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"82121","projectManager":"Buscher, Michael (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Data Sales (Quartz/Quigley/Quiznos)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Buscher, Michael (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"US Air Force Medical Modeling & Simulation Training (AFMMAST) - 10919","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10919","projectManager":"Lewis, Patricia (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"KWEB (10869)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10869","projectManager":"Buscher, Michael (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FED CTE (1011027)","projectDescription":"Cyber Security Training (Instructor-led), Interactive Multi-media (virtual world), Project Management","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":null,"customer":"2;#DHS","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CRANE JXT SOFTWARE SPT - 10835.FC01","projectDescription":"Software Engineering, Development, Programming and Network Support.  This task consists of Network design, implementation, troubleshooting, analysis, and maintenance of G-BOSS's network. This also encompasses the software development required to integrate Cursor on Target (CoT) in to the G-BOSS 2.0 Software Baseline (EBRISS 4.0).  CoT is an XML schema for time-sensitive position information such as spot reporting, blue force tracking, and relocation requests.  Time-sensitive information that specifies the what, when and where information is considered critical, especially in asymmetric warfare arenas such as Iraq and Afghanistan.  Agility and responsiveness are the keys to military superiority.  The CoT event data model defines a terse XML schema and sub-schema extensions for exchanging time-sensitive positions of moving objects. The schemas are arranged in an object model with the intention of simplifying application development.  Rudimentary entities, such as event, detail, and points with limited attributes, are sufficient for almost 90 percent of all information transfers needed for battle management.  These entities can be further extended to provide additional details where necessary.  This allows smarter applications to exchange information beyond these rudimentary objects.  There will be two primary software development pieces.  The first piece will involve the production of an EBRISS driver to interface with CoT compliant external interfaces and all necessary modifications to the EBRISS server.  The second piece is the possible addition of a GUI widget to the EBRISS Client and all GUI control and visualization support for UAV Platform and Sensor Point of Interest CoT messages.  The final element of this task would include any necessary EBRISS Client infrastructure changes to communicate with the server.","businessUnit":"2;#TCE","projectNumber":"10835","projectManager":"Lewis, Patricia (HII-TSD)","customer":"18;#USN","customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Rock Island - 11099","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11099","projectManager":"Lewis, Patricia (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AFNIC CDSO ","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10786/10950","projectManager":"Lewis, Patricia (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Brigade Modernization Command - 10979.001","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10979","projectManager":"Davis, Kirk (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"EUTELSAT Satellite Program - 10772","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10772","projectManager":"Davis, Kirk (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"INMARSAT Satellite Programs - 83258","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"83258","projectManager":"Davis, Kirk (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AMSO Service Support II - 10941","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10941","projectManager":"Rench, Lee (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NETC - (10775/11061/11047)","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10775/11061/11047","projectManager":"Shambora, Mary (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"TRAINING SYSTEMS SW (LOCKHEED) - 10838","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10838","projectManager":"Montero, Leonor (HII-TSD)","customer":null,"customerDetail":null,"contractType":"2;#CPFF LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USPTO OPIM (1011022)","projectDescription":"Project Management (business analysis and oversight).  AGILE SME, SLDC Artifact Collection","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"McMinn, Denise (HII-TSD)","customer":"20;#USPTO","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USAACE Air Traffic Control - 11105","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11105","projectManager":"Shambora, Mary (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FAA UAS SPT-LONESTAR - 10936","projectDescription":"Act as the Lead Systems Integrator (LSI) for the State of Texas as one of six congressionally mandated Unmanned Aerial Systems (UAS) test sites. Provide engineering, programmatic, range operations, and technical expertise in support of the testing and research objectives of the Federal Aviation Administration (FAA) with the intent to safely integrate unmanned aircraft into the National Airspace System (NAS).","businessUnit":"3;#P&I","projectNumber":"10936","projectManager":"Casey, Jason (HII-TSD)","customer":"11;#Texas A&M","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Anti Access Area Den - 11021 (C12947)","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11021","projectManager":"O'Connor, Matthew (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USPTO SIRA Support (1010984)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"McMinn, Denise (HII-TSD)","customer":"20;#USPTO","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USMC CSP CBRN SPT (11001)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11001","projectManager":"Waller, John (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CBRNE Consequence Management (10917)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10917","projectManager":"Nicoli, Joan (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"RDECOM","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Nicoli, Joan (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"COSMIC NCR - IADS - 10315.G05","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10315","projectManager":"Brooks, John (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Ft. Rucker Spt - 10057.058","projectDescription":"The objective of this task order is to provide on-site technical and analytical support to the Program Executive Office (PEO) Aviation, the Concept and Requirements Directorate, (CRD), Ft Rucker AL, The U.S. Army Aviation Center  of Excellence (USAACE), in support of the TRADOC Capability Managers (TCMs),  Aviation Project Management Offices (PMOs) for Apache Attack Helicopter (AAH), Cargo Helicopter and the Product Manager for Aviation Ground Support Equipment (AGSE) in the Aviation Systems PMO; and to provide on-site support for PEO-AVN Headquarters in Huntsville, AL. Technical support of these major Army weapons systems, TRADOC Capability Manager (TCM-R/A, TCM-Lift/Cargo, TCM Unmanned Aerial Systems (UAS) and PM AGSE requires extensive and diverse technical expertise and short term analytical technical support for the National Personnel Security System (NSPS) training program. This also includes support for the Objective Force, Future Combat Systems, and participation in Initial Operational Test and Evaluation (IOT&E) evaluations, Limited User Test (LUTs), Advanced Warfighting Experiments (AWEs) and Advanced Concepts and Technical Demonstrations (ACTDs). Both the Apache and Cargo weapons systems have been fielded in significant number and are undergoing performance, durability and quality engineering changes based upon its fielded performance. AGSE is fielded everywhere aviation is based. It will also provide some administrative support for Headquarters, PEO-AVN.  ","businessUnit":"2;#TCE","projectNumber":"10057","projectManager":"Brooks, John (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Apache Programmatic Spt - 10880.001","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10880","projectManager":"Brooks, John (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"4;#FFP LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FMS Apache - 10057.057","projectDescription":"The Camber staff has supported the International Apache Office, within the Apache Project Office, continuously over the past 15 years, providing program management, systems engineering, sustainment planning and execution for the world-wide Apache fleet consisting of 14 individual active country programs.  During the FMS planning stage, analysis of alternatives to meet the country operational and budgetary goals are evaluated, and the development and integration of unique capabilities are presented with alternatives for country consideration.  Drafts for the development of a total package to establish a full operational capability is conducted and merged with full pricing and associated schedules.  Upon, security assistance review and country acceptance, the Camber staff executes the FMS case with coordination and contracting actions to ensure cost, schedule, quality and performance documented is obtained.        ","businessUnit":"2;#TCE","projectNumber":"10057","projectManager":"Brooks, John (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"SEAPORT-E INTGR TRNS SYS ENG - 10835.0006/10917.0002","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10835/10918","projectManager":"Marshall, Kimberly (HII-TSD)","customer":null,"customerDetail":null,"contractType":"2;#CPFF LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Apache Sensors - 10957.017","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10957","projectManager":"Brooks, John (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"BFT Wharehouse Spt - 10901","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10901","projectManager":"Brooks, John (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"MAE (Med Alt Endurance) - 10557.020","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10557","projectManager":"Brooks, John (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"PM Cargo - 10931.004","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10931","projectManager":"Brooks, John (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"C4ISR TRAINING PRODUCTS AND RELATED SERVICES SUPPORT ","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":null,"projectManager":"Battle, Keith (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NAVAIR 7.2.6 CYBER SEC SP (11067)","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11067","projectManager":null,"customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AO Mainframe Support/LA Systems (1001927)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":"1001927","projectManager":"Green, Jillian (HII-TSD)","customer":"1;#AOUSC","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ACB BLAST","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Fitzwater, Eric (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AIRWORKS Program Office Spt - 11011","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11011","projectManager":"Fitzwater, Eric (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USAF ISR-U2 (10953.0003)","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10953","projectManager":"Ramey, Eliot (HII-TSD)","customer":null,"customerDetail":null,"contractType":"4;#FFP LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"COCOM Spt - 10057.T05/10957.012/10224.033","projectDescription":"Provide technical and training service support to US Pacific Command (USPACOM), US Central Command (USCENTCOM), US Southern Command (USSOUTHCOM) and US Transportation Command (USTRANSCOM) in the implementation of the Joint Training System (JTS), ","businessUnit":"3;#P&I","projectNumber":"10057/10957/10224","projectManager":"Pellecchia, Eugene (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ARDEC RISK MGT SPT - 11015","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11015","projectManager":"Fitzwater, Eric (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"PM CAS - 11007","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11007","projectManager":"Fitzwater, Eric (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CTL (10878)","projectDescription":"Camber's Conformance Test Laboratory (CTL) operates as a third party conformance test laboratory to provide conformance testing in support of the Critical Reagent Program's (CRP) mission.  Camber's CTL has been instrumental in developing the unique processes and procedures used for the conformance testing of CRP lateral flow immunoassays(LFI) used in a variety of detection platforms (i.e. HHA, JBPDS, and JPS).  Prior to the existence of the Camber CTL, a formalized third party QA/QC process did not exist in the acceptance of the manufactured LFI and electrochemiluminescence (ECL) assays. Camber's CTL provides Conformance Test Reports (CTR) to CRP and provides other testing support as directed. Camber's CTL has a Quality Management System (QMS) that is accredited to ISO-17025, which is a standard used for calibration and testing laboratories.  The accreditation meets or exceeds the requirements of ISO-9001.  The CTL has a Secret level facility clearance granted by the Defense Security Service, and all CTL staff members have Secret level personnel security clearances.","businessUnit":"3;#P&I","projectNumber":"10878","projectManager":"Graves, Carcie (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Steelyard (10862)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10862","projectManager":"Roberts, Bruce (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"FMS Taiwan Han Kuang Spt - 11018","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11018","projectManager":"Pellecchia, Eugene (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CCMR HYBRID (11069)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11069","projectManager":"Sweeney, Thomas (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CCMR GPOI (11097)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11097","projectManager":"Sweeney, Thomas (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"VBA Skills Certification Testing - 10958","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10958","projectManager":"Faben, Carol (HII-TSD)","customer":null,"customerDetail":null,"contractType":"4;#FFP LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CCMR In-Residence (11109)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11109","projectManager":"Sweeney, Thomas (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AED Maintenance Engineering Spt - 10931.001","projectDescription":"Provide Technical Support & Engineering Services for the Aviation Missile Research, Development and Engineering Center (AMRDEC), Aviation Engineering Directorate (AED), Maintenance Engineering Division (AEM).  This support provides a broad spectrum of engineering and technical support encompassing maintenance policies and procedures; upgrades and repairs; technical data revision/ improvement; prototyping, and corrosion prevention and control. Our experts will develop and implement new maintenance concepts in support of Army and multi-service aircraft, associated power plants, components and subassembly items. Continue to improve procedures and processes through frequent and vigilant observation while visiting depot repair shops. Assist the depot artisans in assuring proper processes are followed and evaluating/ resolving engineering related production problems affecting quality and schedule. Our field and depot liaison engineering services to the Army, Navy, Air Force and FMS will keep the warfighter equipped with the world's best quality aircraft and components.","businessUnit":"2;#TCE","projectNumber":"10931","projectManager":"Roberson, Rebecca (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"UHPMO Programmatic Spt - 10234.038","projectDescription":"Provides Foreign Military Sales (FMS) support for Blackhawk within the UHPO, PEO Aviation.  ","businessUnit":"2;#TCE","projectNumber":"10234","projectManager":"Roberson, Rebecca (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AED Mission Equipment Division Programmatic Spt - 10931.006","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10931","projectManager":"Roberson, Rebecca (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"OneSAF I2S - 10729.003/11070.00","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10729/11070","projectManager":"Frye, Charles (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"BSSG (11046)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"11046","projectManager":"Parkinson, David (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Force Risk Reduction (FR2)  11029/11031","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11029","projectManager":"Kanahele, Curtis (HII-TSD)","customer":null,"customerDetail":null,"contractType":"2;#CPFF LOE","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"R2TD (10954)","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":"10954","projectManager":"Holliday, David (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Tech Loop Spt - 10057.060","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10057","projectManager":"Roberson, Rebecca (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AED Propulsion Spt - 11009.002","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11009","projectManager":"Roberson, Rebecca (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CCAD Production Spt - 10931.002","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10931","projectManager":"Roberson, Rebecca (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"LCMC Cost Analysis Spt - 10466.120","projectDescription":"Cost analysis, analytical and technical services and products for the TACOM Cost and Systems Analysis (C&SA) office. Technomics provides services in the areas of cost, economic, and technical analysis of major weapon system programs of the Department of Defense. These services include cost, economic, and technical analysis for combat support  and ground combat weapon systems, information management systems, as well as associated acquisition/financial management reporting. This task became much larger and complex on the administrative side than was anticipated. Once we adapted our up-front approach for processing each subtask request, the execution phase flowed nicely without any issues. The customer was pleased with our quality of product/services, schedule compliance, cost control, and business relations.","businessUnit":"2;#TCE","projectNumber":"10466","projectManager":"Davis, Kirk (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"HERCULES FSR SUPPORT - 10631","projectDescription":"The HERCULES Support Task provided to BAE (UDLP) and the government the required experience to efficiently and effectively deprocess, issue and train gaining units on the M88A2 tank retriever.  The government had fielded an all military team but due to the constant turnover of personnel and their lack of hands on experience the Customer PM HBCT transitioned to the current model of long term civilian contractor team.  This also enables a closer relationship between the OEM and the fielding team.","businessUnit":"2;#TCE","projectNumber":"10631","projectManager":"Davis, Kirk (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AETC OPS TRAINING - 10761","projectDescription":"The purpose of this task order is to provide Operations Training Analysis Support Services to the Requirements & Resources Division, Operations Directorate, at Headquarters Air Education and Training Command (HQ AETC), Randolph AFB, TX. The support is to provide contract support to ensure adequate resources are planned for, programmed for, and budgeted for all AETC flying and technical training activities. The contract shall supply two positions. This contract will provide on-site support of AETCs mission by providing analysis, assessment and management associated with the technical and flying training funding activities. To address the tasking identified above, HQ AETC is requesting necessary assessment, analysis, and database management services to support HQ AETCs Budget and Programs Branch. In providing this support, the contractor shall interface with relevant members of the HQ AETC staff, other USAF major commands","businessUnit":"2;#TCE","projectNumber":"10761","projectManager":"Davis, Kirk (HII-TSD)","customer":"14;#USAF","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NORTHCOM Training & Exercise Spt - 10788","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10788","projectManager":"Davis, Kirk (HII-TSD)","customer":null,"customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"JUPITR LOGISTICS SUPPORT","projectDescription":null,"businessUnit":"3;#P&I","projectNumber":null,"projectManager":"Anderson, Lee (HII-TSD)","customer":null,"customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"DOJ/ATF Network Mgmt Svcs (1011039)","projectDescription":"Network Support Services, Campus Work Station Support ","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"4;#DOJ/ATF","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ATG Battle Lab (11038)","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"11038","projectManager":"Leverman, Arron (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"DISA FSO (10982)","projectDescription":null,"businessUnit":"2;#TCE","projectNumber":"10982","projectManager":"Lewis, Patricia (HII-TSD)","customer":null,"customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USPS OIG Support (1010944)","projectDescription":null,"businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Meylan, Jared (HII-TSD)","customer":"19;#USPS","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ITAS - 10971","projectDescription":"Tactical Training Group Pacific (TTGP) has a continuing requirement to provide the US Pacific Fleet with training to conduct effective naval and joint operations across the spectrum of combat operations. TTGPs mission is to provide advanced tactical training to improve war-fighting proficiency to meet the unified commanders requirements. This training requirement spans individual units, Amphibious Readiness Groups (ARG), Carrier Strike Groups (CSG) and Carrier Strike Forces (CSF).","businessUnit":"2;#TCE","projectNumber":"10971","projectManager":"Leverman, Arron (HII-TSD)","customer":"18;#USN","customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CTMMC (10742)","projectDescription":"a. Continuity of Operations (COOP) Planning","businessUnit":"3;#P&I","projectNumber":"10742","projectManager":"McGivern, Brian (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AF Mod & Sim Svc Spt - AFMS3 (10953.0001)","projectDescription":"The purpose of this Task Order (TO) is to provide specialized Modeling & Simulation Support in the Live, Virtual and Constructive (M&S/LVC) operational, technical, and innovative support services for the Joint M&S Community to assist in the Government's integration of Live training with realistic simulation environments. The Air Force Life Cycle Management Center (AFLCMC) at Wright-Patterson Air Force Base, OH is the lead organization supported by this TO. Previously Air Force Agency for Modeling and Simulation was the primarily supported organization. This TO provides support to the Joint M&S Community mainly composed of AF and other Department of Defense (DoD) organizations, but at times may support other Federal agencies. ","businessUnit":"2;#TCE","projectNumber":"10953","projectManager":"Ramey, Eliot (HII-TSD)","customer":"14;#USAF","customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USSS Einfo Extranet Support (1010952.0001)","projectDescription":"Management, support and development of the USSS eInformation Network","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Fisher, Virginia (HII-TSD)","customer":"21;#USSS","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"JMASS III/IV - AO (1001850/1010981/1011040/1011063)","projectDescription":"IMSG provides high-end IT professional services to the Administrative Office of US Courts, including full life cycle software development, application support, database support, enterprise infrastructure support,  migration of major systems to improve business processes, help desk, maintenance support services, planning and analysis, project management, independent verification and validation (IV&V),  Agile software and systems engineering","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Jacobs, Chris (HII-TSD)","customer":"1;#AOUSC","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Airbus D&S Satellite Programs","projectDescription":"PROGRAM MANAGEMENT","businessUnit":"2;#TCE","projectNumber":"83259","projectManager":"Davis, Kirk (HII-TSD)","customer":"23;#Airbus","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USPS Engineering Helpdesk (1011004)","projectDescription":"Provide hardware and software technical support for about 12,000 DSS and 4,200 PASS machines","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Meylan, Jared (HII-TSD)","customer":"19;#USPS","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"USPS SEDS (1010972)","projectDescription":"Broad range of engineering and information technology business needs for multiple USPS organizations","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Meylan, Jared (HII-TSD)","customer":"19;#USPS","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AFNET ","projectDescription":"Camber provides services in Customer Relationship Management, Certification and Accreditation Project Management, Network Validation, Network Engineering, and Network Architecture in support of the Air Force, Air Force Space Command (AFSPC), and the 24th Air Force Cyber Command (AFCYBER) missions. Specific services provided by Camber include&#58;","businessUnit":"2;#TCE","projectNumber":"10801","projectManager":"Lewis, Patricia (HII-TSD)","customer":"14;#USAF","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"NETCENTS CMOS OLVIMS (10951)","projectDescription":"Camber Corporation, as a subcontractor to DSD Laboratories, provides technical support to the Air Force's Cargo Movement Operations System (CMOS) and the On-Line Vehicle Interactive Management System (OLVIMS).  ","businessUnit":"2;#TCE","projectNumber":"10951","projectManager":"Lewis, Patricia (HII-TSD)","customer":"14;#USAF","customerDetail":null,"contractType":"3;#FFP","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"CRANE MEW Towed Decoy - 10832.FC01","projectDescription":"Decoy Launching System MK 36 (Super Rapid Blooming Offboard Countermeasures) sustainment/disposal support. ","businessUnit":"2;#TCE","projectNumber":"10832","projectManager":"Lewis, Patricia (HII-TSD)","customer":"18;#USN","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Waterfront Team Trn Spt (10850.0041/11081.00)","projectDescription":"Provide Waterfront Team and Maintenance Training support and Management","businessUnit":"2;#TCE","projectNumber":"10850","projectManager":"Briggs, Reginald (HII-TSD)","customer":"18;#USN","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Department of Education (1001935)","projectDescription":"Provide comprehensive Web Support Services to the Department of Education for the Department's public-facing internet and intranet Scope of services includes the following areas: project management, system engineering and design support, software/web development support, system development support, data analysis, quality and management support, training and documentation support, systems security and information assurance support, and emerging technologies support. ","businessUnit":"1;#DMIT","projectNumber":"1001935","projectManager":"Rench, Lee (HII-TSD)","customer":"3;#DoEd","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"MDA PRIDE - 10661.004","projectDescription":"Camber is a subcontractor on the ESC Federal, Inc. team supporting the Missile Defense Agency (MDA) Agency Business Operations Directorate in implementing, integrating, maintaining, and continually improving MDA financial systems and processes. ","businessUnit":"2;#TCE","projectNumber":"10661","projectManager":"McDonald, Russ (HII-TSD)","customer":null,"customerDetail":null,"contractType":"1;#CPFF","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"Fairfax County Courts CARS (1001727/1011051)","projectDescription":"Camber team supports FCC's CARS System, which in turn serves the general public through web based document indexing, storage & retrieval of court documents including land records, probate, marriage licenses, judgments  offices etc.","businessUnit":"1;#DMIT","projectNumber":null,"projectManager":"Rench, Lee (HII-TSD)","customer":"6;#Fairfax County","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"AMCOM LOGSA LITE","projectDescription":"As a member of Team IBM, Camber provides the United States Army Logistics Support Activity (LOGSA) high quality, efficient and effective Information Technology (IT) services that include software development, database management and analysis, application integration, business case analysis, IT project management, and systems operations and maintenance. Camber currently employs a full time staff of 33information systems professionals on site to LOGSA at Redstone Arsenal. Our team assists LOGSA in supporting the Logistics Information Warehouse (LIW), which has been designated as the official authoritative repository for Army logistics data.  LOGSA and its LIW suite of products and services provide the Army community with vital logistics data necessary for the planning, conduct, and sustainment of war fighting capability worldwide.  Specific areas of Camber support are as follows&#58;","businessUnit":"2;#TCE","projectNumber":"10823","projectManager":"McDonald, Russ (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ADM (10614)","projectDescription":"Camber provided the ECBC Engineering Directorate's ADM Division with the following: project management (including requirements definition); requirements analysis; project status reporting; market research; technical support; detailed component and systems design and engineering (including engineering packages, 3D modeling, rapid prototyping, fabrication and manufacturing); systems integration; fielding; and logistical support/sustainment across the wide spectrum of tasks for which the ADM Division is responsible. ","businessUnit":"3;#P&I","projectNumber":"10614","projectManager":"Goodwin, Timothy (HII-TSD)","customer":"13;#USArmy","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"ESSO-Silentroar (10879/10864)","projectDescription":"The purpose of this contract was to provide subject matter experts (SMEs) possessing military mission and technologic expertise to aid SILENTROAR in fulfilling the National Security Agency (NSA)/Central Security Service (CSS) goal of fully developing and integrating the extended cryptologic enterprise to provide dominant Signals Intelligence (SIGINT) capabilities to our US Military and its partners. ","businessUnit":"3;#P&I","projectNumber":"10879","projectManager":"McConaghy, Tim (HII-TSD)","customer":"9;#NSA","customerDetail":null,"contractType":null,"contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null},
        {"projectName":"VBA TPSS Training Evaluation & Management - 10900","projectDescription":"The Department of Veterans Affairs (VA) through the Veterans Benefits Administration (VBA), Technical Training and Evaluation Office (TT&E) (NOTE: In 2015, the name was changed to Training and Performance Improvement Directorate, TPI) requested support for the purpose of creating , updating, or implementing all phases of the Instructional Systems Development process; Technical Training and Performance Support System (TPSS) products; and providing related training infrastructure support and evaluation for VBA training efforts. This project is a continuation of VBA's existing TPSS and training event support for all services designed to provide training and performance support to VBA employees on critical job tasks. VBA has identified six tasks necessary to accomplish the TPSS and training event support.","businessUnit":"2;#TCE","projectNumber":"10900","projectManager":"Mellone, Ingrid (HII-TSD)","customer":"22;#VA","customerDetail":null,"contractType":"5;#T&M","contractValue":null,"practices":[],"placeOfPerformance":null,"primeContractor":null,"primeContractorName":null,"securityClearedWork":null,"securitySCIF":null,"technicalLead":null}
    ]

    return util
})